url: "https://www.wlast.org" # the base hostname & protocol for your site, e.g. http://example.com

baseurl: "" # the subpath of your site, e.g. /blog

title: "Western Loudoun Art & Studio Tour" # the name of your site, e.g. ACME Corp.

description: "The 16th annual Western Loudoun Art and Studio Tour is on for the weekend of June 2-4, 2023. During this event over 50 western Loudoun VA artists and guest artists open their studios to the public for exhibition and sale of their work."

sass:
    load_paths:
        - _sass

collections:

  artist:
    output: true


defaults:

  - scope:
      path: ""
      type: "artist"
    values:
      layout: "artist"


  - scope:
      path: ""
    values:
      layout: "default"
